### PR TITLE
add inital dark mode

### PR DESCRIPTION
**Pull request by HoloPollock**

### CODE REVIEW

**Comment by HoloPollock** [comment]
I think some colour should change like the input box and the empty photo colour just didn't know yet

**Comment by qjack001** [comment]
input box can stay light, as it works better for accessibility anyway. Submit button should be the same color as the text, though.  

screenshot

The different text color for the link is weird. Should be consistent.  

screenshot

The problem is exacerbated at the bottom, where there end up being 5 different shades of grey-ish blue. I would keep the accent blue as is, and the footer text is fine too. The paragraph text, movie title link text, and support button should all be the same color. Whatever color you end up going with can also be the color you use for the background of the poster

screenshot

**Comment by HoloPollock** [comment]
All the link text colour is the same I took the "light mode" colour and lighted it as in light mode they are different colours then standard text. But makes sense

**Comment by qjack001** [comment]
Ya that makes sense, but it is too noticeable in the dark scheme. Should there also be a toggle?

**Comment by HoloPollock** [comment]
if there should be a toggle where should it go its not very obvious

**Comment by qjack001** [comment]
```
.dark body {...}
.dark #app {...}
```

this doesnt work because it means a `body` element inside of a `.dark` element, and a `#app` element in a `.dark`. In the code, the `.dark` is in the body, and _is_ the `#app`. Try applying the class to the body, and changing that css to `body.dark`.

**Comment by HoloPollock** [comment]
I cant apply to body its vue 😆 you dont have access to body

**Comment by qjack001** [comment]
also, I think the non-hovered submit button should be `#526e89`, not black.

**Comment by qjack001** [comment]
> I cant apply to body its vue 😆 you dont have access to body

you do in javascript tho

**Review by qjack001 — CHANGES_REQUESTED** [review]
Ya this is too hack-y. Just use JS to toggle a class on the body (`document.body.classList.toggle('darkmode')`) and let the colors be defined in the css

**Comment by HoloPollock** [comment]
> Ya this is too hack-y. Just use JS to toggle a class on the body (`document.body.classList.toggle('darkmode')`) and let the colors be defined in the css

I can't do this becuase I'm not uses a vue property so it doesn't tell the child components to update

**Comment by HoloPollock** [comment]
dont merge sumbiting breaks it

**Review by qjack001 — APPROVED** [review]

**Pull request merged**
