### PR TITLE
fix design bug

### PR DESCRIPTION
**Pull request by 1netanel**
added pointer cursor to dark mode button and fixed "support this site" button width

### CODE REVIEW

**Comment by HoloPollock** [comment]
Hey I can check this out if you want your error had to do with your lock file and pnpm and not your changes. Thanks for the commit

**Comment by 1netanel** [comment]
sure. do you need me to do anything ?

**Comment by HoloPollock** [comment]
No it’s ok I can take over this PR if that’s ok with you

**Comment by 1netanel** [comment]
Sure, thanks

**Pull request closed without merging**
