### PR TITLE
add loading check don't resubmit when loading

### LINKED ISSUE #11: Overwrites movie
Hitting <kbd>submit</kbd> multiple times triggers multiple submit events, and the random movie result ends up getting overwritten by the later requests. At best it makes the experience feel kind of buggy, at worst, the input changed and the first result(s) are incorrect. This might also be a problem for people who choose to "double click" on things.

**Solution:** The `submit()` method should cancel all previous requests, so only the last one shows up. If possible, the loading bar should reset as well.

### PR DESCRIPTION
**Pull request by HoloPollock**
this should fix it closes #11

### CODE REVIEW

**Comment by HoloPollock** [comment]
the thing to keep in mind with this is it introduces a stuck condition on the site where it didn't exist before hand

**Comment by HoloPollock** [comment]
@qjack001 Do we think we should do this

**Comment by qjack001** [comment]
I just don't love it. It stops you from editing your search to a new search while it's loading, which I think a lot of people might do since they just go to the url.

I would want it to disregard any API responses, if a new request has been made, instead of freezing submit.

**Review by qjack001 — CHANGES_REQUESTED** [review]
Make it not enter a stuck state

**Comment by HoloPollock** [comment]
> I just don't love it. It stops you from editing your search to a new search while it's loading, which I think a lot of people might do since they just go to the url.
> 
> I would want it to disregard any API responses, if a new request has been made, instead of freezing submit.

wait it doesnt stop you from editing it just stops you from hitting the submit button

**Comment by HoloPollock** [comment]
Try this
```js
callApi(params) {
    let requestNum = hash(params) + System.now
    globalRequestNum = requestNum
    fetch("https://api.watchlistpicker.com/" + params)
    .then(f(response) {
        if(respons.status == 200 && globalRequestNum == requestNum) {
            //update film
        }
    })
}
```

**Comment by HoloPollock** [comment]
lol the time thing breaks verify

**Comment by HoloPollock** [comment]
becuase you are not checking the hash at the same time when the hash was made

**Comment by HoloPollock** [comment]
@qjack001 Let me know what you think now

**Review by qjack001 — APPROVED** [review]

**Comment by qjack001** [comment]
The app takes a really long time if you spam the submit button really fast

**Comment by HoloPollock** [comment]
Do we think it's worth it then ( I don't know why that happens)

**Comment by HoloPollock** [comment]
It seems server side oddly though because I got a Logdna alert

**Comment by qjack001** [comment]
> It seems server side oddly though because I got a Logdna alert

lets push it. But make a new issue to look into further

**Comment by qjack001** [comment]
> > It seems server side oddly though because I got a Logdna alert
> 
> lets push it. But make a new issue to look into further

@HoloPollock ?

**Comment by HoloPollock** [comment]
Oh sorry I forgot lol

**Comment by HoloPollock** [comment]
I'll do the merge tomorrow

**Pull request merged**
