### PR TITLE
Vercel func test

### PR DESCRIPTION
**Pull request by HoloPollock**
this is a test for using vercel function in an attempt to lower costs. feel free to play around with it. we should talk about pro and cons before this merge though

### CODE REVIEW

**Comment by qjack001** [comment]
looks good to me, just see if we can port the usage metrics.

**Comment by HoloPollock** [comment]
I added logging to vercel should I merge

**Comment by HoloPollock** [comment]
I'm gonna hold off its logging alot and is annoying

**Comment by HoloPollock** [comment]
so I think what we should do is move over to this see what the loggin looks like with this and if its less that what we want we move back to google @qjack001  what do you think

**Comment by HoloPollock** [comment]
I switched to a better logging service its much better filtering

**Pull request merged**
