### PR TITLE
Add handeling of ignore unreleased films

### PR DESCRIPTION
**Pull request by HoloPollock**
backend added

### CODE REVIEW

**Comment by HoloPollock** [comment]
@qjack001 in classic me it works the styling is a little whacky

**Comment by qjack001** [comment]
Lmao

**Comment by HoloPollock** [comment]
yah I wanted it to be on its own line but the labels are whaky with margin

**Comment by HoloPollock** [comment]
> yah I wanted it to be on its own line but the labels are whaky with margin

becuase they are inline right?

**Comment by HoloPollock** [comment]
@qjack001 we should do the no film found logic on the frontend so we dont need to find a new error code lol

**Comment by qjack001** [comment]
Yes I 100% agree

**Comment by HoloPollock** [comment]
@maxkele If you want to play with css this is another good. Place to try to fix the weird layout here

**Comment by qjack001** [comment]
Made some tweaks. Not totally satisfied with where the footer is sitting, but not sure how you are positioning it enough to fix it.

**Comment by qjack001** [comment]
also I swear 10% of the time I get "no film found" when the setting is turned on. Not smart enough to figure out why

**Comment by HoloPollock** [comment]
> also I swear 10% of the time I get "no film found" when the setting is turned on. Not smart enough to figure out why

found out why I was using the wrong length of list so sometimes will be out of bounds will fix

**Comment by HoloPollock** [comment]
We need to add the url param thing for ignore unreleased

**Comment by qjack001** [comment]
> We need to add the url param thing for ignore unreleased 

Yes. That, the updated 404 message, and the positioning of the footer

**Comment by HoloPollock** [comment]
> > We need to add the url param thing for ignore unreleased
> 
> Yes. That, the updated 404 message, and the positioning of the footer

also the merge conflict is not super trivial to fix

**Comment by HoloPollock** [comment]
I think I did the merge correct

**Comment by HoloPollock** [comment]
> I think I did the merge correct

after the merge the contract on the note text is pretty low in dark mode

**Comment by qjack001** [comment]
> > I think I did the merge correct
> 
> after the merge the contrast on the note text is pretty low in dark mode

The contrast should be improved from before :/

**Comment by qjack001** [comment]
@HoloPollock you're right, I switched the paragraph text to match the submit button and it's too low. #44 should remedy (I think it still visually matches the color of the submit button).

**Comment by HoloPollock** [comment]
> @HoloPollock you're right, I switched the paragraph text to match the submit button and it's too low. #44 should remedy (I think it still visually matches the color of the submit button).

yah seems good (I just merged #44 in to main then main here because it was small and then we could check)

**Comment by HoloPollock** [comment]
the contrast is better still not amazing but not bad

**Review by qjack001 — CHANGES_REQUESTED** [review]
> > We need to add the url param thing for ignore unreleased
> 
> Yes. That, the updated 404 message, and the positioning of the footer

**Comment by qjack001** [comment]
image

**Comment by qjack001** [comment]
@HoloPollock also i added the update to see if anything would happen with percy.. seems like no

**Comment by HoloPollock** [comment]
@qjack001  what do we have left for this

**Comment by qjack001** [comment]
> @qjack001  what do we have left for this

- url param
- footer position

**Comment by HoloPollock** [comment]
@qjack001 do you want to footer lower??

**Comment by HoloPollock** [comment]
the if statement added in this commit is kinda gnarly if you know a better way please do but push state didnt seems to do what I wanted

**Comment by qjack001** [comment]
> @qjack001 do you want to footer lower??
> 

No, I think it's too low. What do you think?

**Comment by HoloPollock** [comment]
I personally never saw it as an issue so I don't know what to change 😆

**Comment by HoloPollock** [comment]
if you want to change change the %%vh in the calc in `#main` in App.vue

**Comment by HoloPollock** [comment]
@qjack001 also this is a another stupid question should the footer change be in this PR seems orthogonal to what's changing here should we try to keep this atomic to what the goal of the PR is

**Comment by qjack001** [comment]
> @qjack001 also this is a another stupid question should the footer change be in this PR seems orthogonal to what's changing here should we try to keep this atomic to what the goal of the PR is

The increase in page size, as a result of the addition of the new advanced search option, has pushed the footer down (at least on desktop). If you want to get this out and done tho, I am ok creating a new ticket to fix the issue and merging this.

**Review by qjack001 — APPROVED** [review]

**Comment by HoloPollock** [comment]
> > @qjack001 also this is a another stupid question should the footer change be in this PR seems orthogonal to what's changing here should we try to keep this atomic to what the goal of the PR is
> 
> The increase in page size, as a result of the addition of the new advanced search option, has pushed the footer down (at least on desktop). If you want to get this out and done tho, I am ok creating a new ticket to fix the issue and merging this.

if its related I understand doing in this PR also I know understand the context better the footer is too low when advanced search fly out  is expanded. this may be hard to do but ill check out how to do it

**Comment by HoloPollock** [comment]
@qjack001 my height change may be a stupid change lol

**Comment by HoloPollock** [comment]
lol yah it forsure breaks mobile 😂

**Comment by HoloPollock** [comment]
yah the height thing makes mobile whacky also on mobile especially the footer feels low

**Comment by HoloPollock** [comment]
after film load changing the css might be the best approach(the min height exists for when film isnt loaded)

**Comment by HoloPollock** [comment]
or we may need media queries

**Comment by qjack001** [comment]
Revert your changes and merge the pr. I think the footer issue is stumbling onto a larger problem (that the way we are placing the footer is too brittle). The solution to that problem will be too large in scope to keep in this pr.

**Comment by HoloPollock** [comment]
cool

**Pull request merged**
