### PR TITLE
pnpm

### PR DESCRIPTION
**Pull request by qjack001**
@HoloPollock — the Vercel install command will need to be overridden in the console to:

```bash
npx pnpm@6 install --shamefully-hoist --store-dir=.pnpm --frozen-lockfile
```

and the build command set to:

```bash
npx pnpm@6 build
```

### CODE REVIEW

**Review by HoloPollock — DISMISSED** [review]

**Comment by HoloPollock** [comment]
done

**Comment by qjack001** [comment]
Sorry it re-requires your review. Needed to force Vercel to try the build again.

**Review by HoloPollock — APPROVED** [review]

**Comment by HoloPollock** [comment]
Wait it doesn't work can I revoke lol

**Review by HoloPollock — CHANGES_REQUESTED** [review]
Doesn't build 404 preview

**Comment by qjack001** [comment]
> Doesn't build 404 preview

Try reloading. Works for me.

**Review by HoloPollock — APPROVED** [review]

**Pull request merged**
