### PR TITLE
Dark Mode toggle

### PR DESCRIPTION
**Pull request by HoloPollock**

### CODE REVIEW

**Comment by HoloPollock** [comment]
lol I tried @qjack001  but im bad

**Comment by qjack001** [comment]
> lol I tried @qjack001 but im bad

oh my god that's spectacular

**Review by qjack001 — CHANGES_REQUESTED** [review]
Needs work, to put it lightly 🤣

**Comment by qjack001** [comment]
Ok I did it. All the form, none of the functionality tho. Tag the svg (`darkmode-icon`) with the `.moon` class to turn it into a moon. Remove to turn back into a sun. I suggest having the moon display in light-mode, and the sun display in dark.

**Comment by HoloPollock** [comment]
I guess I should figure out how to do local storage to save the pref 😂

**Comment by qjack001** [comment]
> I guess I should figure out how to do local storage to save the pref 😂

I think you'll find it's less work than you would think

**Comment by HoloPollock** [comment]
@qjack001 pls actually review my local storage logic 😂

**Comment by HoloPollock** [comment]
also we should merge the colour change before this one just incase

**Comment by qjack001** [comment]
It does not work

**Review by qjack001 — APPROVED** [review]

**Comment by HoloPollock** [comment]
@qjack001 can I merge the colour before this

**Pull request merged**
