### PR TITLE
Implement film length options frontend

### LINKED ISSUE #81: Fix `ignoreUnreleased` param

### LINKED ISSUE #82: Add Advanced Options for film length
Implements #78

### PR DESCRIPTION
**Pull request by qjack001**
UI portion of #78. Closes #82. Dependant on merge of #79 for logic and #80 for current codebase. Also closes #81.

### CODE REVIEW

**Comment by qjack001** [comment]
Ah sorry, didn't realize the diff would be huge if I based it off the refactor. Really the only changes are in `App.vue`'s logic for getting the url params, setting url params, building api endpoint, and in `AdvancedOptions.vue` (obviously).

**Comment by HoloPollock** [comment]
can you cancel this and just add it after merge of refactor

**Comment by HoloPollock** [comment]
I feel like will cause whacky things on merge

**Comment by HoloPollock** [comment]
oh lol I see your right it isnt binary of short or feature I though you would have to one or other lol

**Comment by HoloPollock** [comment]
I will fix on my side

**Comment by qjack001** [comment]
> I will fix on my side

Lol, just added a comment on your origional PR about it

**Pull request closed without merging**
