### PR TITLE
fix intersect issue

### PR DESCRIPTION
**Pull request by HoloPollock**
this should fix it based how I noticed the logic issue

### CODE REVIEW

**Comment by HoloPollock** [comment]
closes #57

**Comment by qjack001** [comment]
Unfortunatly, I've seen it...

image

**Comment by HoloPollock** [comment]
oh k more work needed :(

**Comment by qjack001** [comment]
> oh k more work needed :(

no!

**Comment by qjack001** [comment]
@HoloPollock it works great and i am stupid! I just frogot to turn the intersection on

**Review by qjack001 — APPROVED** [review]

**Comment by HoloPollock** [comment]
oh lol

**Pull request merged**
