### PR TITLE
Advanced search

### PR DESCRIPTION
**Pull request by HoloPollock**

### CODE REVIEW

**Comment by qjack001** [comment]
this looks really good

**Comment by qjack001** [comment]
What happens if there is no film in the intersection, tho?

**Comment by HoloPollock** [comment]
um probably the thing that happens when you have no films in a list

**Comment by qjack001** [comment]
cool, the only thing that needs work is the accessibility. When you tab through the options you cycle through the radio buttons even if they are hidden. Also its not clear to a screen reader what the "Advanced Search" does/reveals—so it needs some ARIA tags.

https://www.w3.org/WAI/tutorials/menus/flyout/

**Comment by qjack001** [comment]
> um probably the thing that happens when you have no films in a list

image

Unfortunately it does not do that

**Comment by HoloPollock** [comment]
> Add accessibility improvments

If you were gonna do a redesign are you gonna add the aria labels or should I

**Comment by HoloPollock** [comment]
> > um probably the thing that happens when you have no films in a list
> 
> image
> 
> Unfortunately it does not do that

Oh interesting Ill check it out

**Comment by HoloPollock** [comment]
> > > um probably the thing that happens when you have no films in a list
> > 
> > 
> > image
> > Unfortunately it does not do that
> 
> Oh interesting Ill check it out

I fixed this but maybe we want to update the copy for this or I can maybe return a different error for this if you want would require for refactoring of the API code 

Screen Shot 2020-10-10 at 10 09 57 PM

**Comment by HoloPollock** [comment]
also I need to make intersect be added to the url param and saved in the main app

**Comment by HoloPollock** [comment]
> also I need to make intersect be added to the url param and saved in the main app

we are using replace state so this may be a bigger change than expected though I'm not very good at this so maybe you know a better way @qjack001

**Comment by qjack001** [comment]
Why would that be a problem? Also re: accessibility, ya I can add it when I update the design. As for the copy, we should have it be specific to the situation. Send a unique error code when the two lists don't intersect and we can respond to that

**Comment by HoloPollock** [comment]
> Why would that be a problem? Also re: accessibility, ya I can add it when I update the design. As for the copy, we should have it be specific to the situation. Send a unique error code when the two lists don't intersect and we can respond to that

what error code should I use since im already using 404

**Comment by qjack001** [comment]
204 would be my pick

**Comment by HoloPollock** [comment]
hey my shit works on chrome but not on safari
Screen Shot 2020-10-10 at 11 42 38 PM
 maybe 204 is a bad idea

**Comment by HoloPollock** [comment]
it seems safari doesnt understand error 204

**Comment by HoloPollock** [comment]
I got it I'm sorry jack for the many many commits

**Comment by HoloPollock** [comment]
the only thing we don't have is an intersection in the file param

**Comment by HoloPollock** [comment]
aswell is do you think the buttons would look good with dark mode

**Comment by HoloPollock** [comment]
> the only thing we don't have is an intersection in the file param

I did this

**Comment by HoloPollock** [comment]
@qjack001 you should add a focus thing its complicated to see when I'm focused for keyboard nav

**Comment by HoloPollock** [comment]
I wanted to request change but I can't

**Comment by qjack001** [comment]
@HoloPollock tried, but it's not really focusable, since it's arrow key navigated

**Comment by qjack001** [comment]
I can add a little though

**Comment by HoloPollock** [comment]
> @HoloPollock tried, but it's not really focusable, since it's arrow key navigated

ahh its its to whack dont worry its just a little weird

**Comment by qjack001** [comment]
ok i did it

**Review by qjack001 — APPROVED** [review]

**Pull request merged**
