### PR TITLE
Improve keybord navigation

### PR DESCRIPTION
**Pull request by qjack001**
Some visual improvements (make things more prominent when focused) and make the dark mode toggle keyboard accessible (#45).

### CODE REVIEW

**Comment by HoloPollock** [comment]
the toggle is no longer clickable
I'm guessing you put a div over it

**Comment by qjack001** [comment]
> the toggle is no longer clickable
> I'm guessing you put a div over it
> aswell it cant be activated with the keyboard just focused

Yep I realized lol. I'm working on a fix I'll let you know how it goes

**Comment by qjack001** [comment]
Ya ok sweet @HoloPollock it's all yours

**Review by HoloPollock — APPROVED** [review]
seems all good seems to work well

**Pull request merged**
